GovWifi/govwifi-authentication-api

- README.md
This should make it easier to understand why we have these extra params coming
across and why we don't just drop them.
> Update README to explain extra parameters

- app.rb
- spec/app_spec.rb
Currently the nature of how we connect to the database is causing the
MySQL connection pool to be exhausted. By initializing the connection as
a constant we an avoid establishing new connections while it remains in
memory.
> Ensure that the MySQL connection pool isn't maxed out

- Dockerfile
- docker-compose.yml
The way we are setting up ECS with the Application Loadbalancer means we
don't have to keep using unique ports.
Existing security groups allow traffic on 8080, so use that instead of defining new security groups
> Listen on 8080

- Jenkinsfile
We've had some "hanging" docker containers on Jenkins that block
other builds - this PR makes sure make stop is always run, even in
cases of the build being aborted or crashing.
> Always perform 'make stop' in Jenkins

- Jenkinsfile
this enables us to run it agentless, so we don't block an executor
Also remove explicit github notifications, as this is handled by multi-branch builds already
> break out deploy check into its own stage

- Gemfile
- app.rb
- config.ru
Sets up [sensible_logging](https://github.com/madetech/sensible_logging) gem which provides:
* Tagged logging
* Request ID (for tagged logging, and to include in Sentry exceptions in future)
* Minimal request log format
Example output from request logging:
```
[localhost] [development] [76b706bf-7f0c-48ec-8045-57a40d5aad82] method=GET path=/healthcheck status=200 duration=0.0207032 params={"test"=>"one", "two"=>"three"}
```
If you reference the built in Sinatra `logger` helper within the app/routes, then you'll see output like:
```
get 'healthcheck' do
logger.debug('testing')
'Healthcheck'
end
```
```
[localhost] [development] [76b706bf-7f0c-48ec-8045-57a40d5aad82] testing
[localhost] [development] [76b706bf-7f0c-48ec-8045-57a40d5aad82] method=GET path=/healthcheck status=200 …
```
> Add sensible_logging gem

- app.rb
We understand that extra API calls are happening here, while we don't
have a solid fix yet, we don't need to print debug output
> Remove extra debugging for auth API

- Gemfile
- Gemfile.lock
- app.rb
- lib/loader.rb
We're making some changes to this API to update the last login value
when someone authenticates.
In order to do this we need a Sequel model, which is going to require
some files in lib.  It makes sense at this point to require all from
lib.
> Move dependencies to loader

- app.rb
- lib/loader.rb
- lib/user.rb
- spec/app_spec.rb
We keep track of last_login to effectively identify inactive users.
This used to be done by the logging API but will now be done by this
API.
This makes it easier to split the userdetails table out of the main
database and be owned by this API.
The definition of "last login" will change as a result of this, and will
effectively be "last login attempt" as we will populate this field for
both access accept and access reject.  I don't see this affecting GDPR
cleanup tasks at all.
> Introduce a user model for the Sequel gem

- app.rb
- spec/app_spec.rb
Preserve this functionality from the logging API.
The health user is exempt from GDPR cleanup, so recording
last_login is not required. Also health checks happen frequently and
will just be unnecessary strain on the database.
> Don't record last login for HEALTH user

- Makefile
- docker-compose.development.yml
- docker-compose.yml
We only want to bind ports while in development, to avoid doing it for in jenkins.
This will allow us to run the tests in parallel
> only bind ports in development

- Jenkinsfile
- When there is a merge to `auth-api/master` it triggers the `acceptance-tests/master` pipeline to be built.
- This runs the acceptance tests on all the dependent master branches.
- If it fails it blocks the deploy, but not the merge.
Exists in the `frontend` already here: https://github.com/alphagov/govwifi-frontend/blob/master/Jenkinsfile#L33
> Run acceptance specs when a merge to master occurs

- lib/loader.rb
We've been running out of connections when under load, so increase the [pool size from 4][2].
This takes us from 12 connections to 48 connections per regional db\*, which is well within our limits\*\*.
16 has been chosen so we can have a DB connection [per thread][1]. Given that this service
is a thin wrapper around the database, the requests will immediately wait. Aligning thread
count with the connection pool size should avoid this issue.
\*: connection count is based on pool size per instance, 3 instances per region
\*\*: limit per db is based on memory size of db. Ours has 4gb, and as defined by the parameter group, is `{DBInstanceClassMemory/12582880}`, which is `(4096*1024*1024)/12582880` which is 341 max connections.
[1]: https://github.com/puma/puma/blob/821905c84587c9f403ebe26bba1 …
> increase the database connection count to 16

- lib/loader.rb
Whilst this has been tested in staging, we've opted to deploy this change out to the Logging API first, which is not on the critical path.
This PR is expected to be reverted after the Logging API change has been tested in production
> Revert "increase the database connection count to 16"

- mysql/Dockerfile
We need to use mysql_native_password, as mariadb client doesn't ship with this yet
> change to using mysql 8

- .rubocop.yml
- Gemfile
- Gemfile.lock
- Makefile
- app.rb
- lib/loader.rb
- spec/app_spec.rb
- spec/spec_helper.rb
- The `govuk-lint` gem is [deprecated](https://github.com/alphagov/govuk-lint/commit/8ef29badd90a1936774657bc89f3a4cb77210e5f)!
- This switches to `rubocop-govuk`, the more up-to-date replacement, using the [migration guide](https://docs.publishing.service.gov.uk/manual/migrate-from-govuk-lint.html).
- Thanks for adopting our linting rules!
- Closes #126.
> Use `rubocop-govuk` for linting instead of `govuk-lint`

- ci/tasks/build-deployable.yml
Add Docker Hub auth token to allow Concourse pipeline task to pull images from Docker Hub.
The pipeline is configured in [govwifi-concourse-deploy-pipeline](https://github.com/alphagov/govwifi-concourse-deploy-pipeline).
We need to do this because Docker Hub will introduce rate limiting on 1 November.
paired: @camdesgov & @sarahseewhy
> Add docker hub credentials to build-deployable

- Gemfile.lock
Bump the `rexml` version because our current version contains security vulnerabilities: 
```
Vulnerable versions: < 3.2.5
Patched version: 3.2.5
The REXML gem before 3.2.5 in Ruby before 2.6.7, 2.7.x before 2.7.3, and 3.x before 3.0.1 does not properly address XML round-trip issues. An incorrect document can be produced after parsing and serializing.
```
Dependabot is failing to make the change and open a PR in Github.
> Manually bump the rexml version

- Gemfile.lock
Reverts alphagov/govwifi-authentication-api#234
> Revert "Bump puma from 5.3.2 to 5.4.0"

- .github/workflows/workflow.yml
Add Github workflow to lint and test our code.
We are migrating our PR pipelines away from Concourse into Github Actions.
Link to Trello card (if applicable): https://trello.com/c/TnxuCVW9/2017-concourse-migration-migrate-linting-pipelines-to-github-actions[](https://github.com/camdesgov)
> Add GitHub action to lint and test our code

- ci/tasks/scripts/deploy.sh
We are in the process of making any references to the authentication api infrastructure consistent, and we are testing this change in Staging. 
At present we are using the name "authentication-api" and "authorization-api" to refer to the same things, which is confusing. This change is part of rectifying that.
Link to Jira card (if applicable): 
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-204
> Change ECS service name in staging

- ci/tasks/deploy.yml
- ci/tasks/scripts/deploy.sh
We are in the process of making any references to the authentication api infrastructure consistent.
At present we are using the name "authentication-api" and "authorization-api" to refer to the same things, which is confusing. This change is part of rectifying that.
Link to Jira card (if applicable):
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-204
> Change ECS service name for entire deploy process

- buildspec.yml
Introduce an AWS Codebuild task permitting us to migrate from concourse to AWS Developer Tools
We need to migrate away from Concourse due to strategic decision to use managed services.
### Jira card (if applicable): 
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?selectedIssue=GW-253
> Introduce an AWS Codebuild task

- README.md
Reverts alphagov/govwifi-authentication-api#303
This PR was a no-op used solely to test a pipeline. The test was successful and so this should be reverted.
> Revert "Add a no op line to test pipeline triggering"

- buildspec.yml
Remove "STAGE" variable from buildspec file
The same docker image will now be used in production and staging. Removing the need for the "STAGE" variable.
> Remove "STAGE" variable from buildspec file

- buildspec.yml
Add Missing Acceptance Tests
The [acceptance tests](https://github.com/alphagov/govwifi-acceptance-tests) were previously part of the Concourse deploy pipeline. They were missed in the original Concourse to AWS migration. This commit adds them back.
> Add Missing Acceptance Tests To AWS Pipeline

- Makefile
- mysql/bin/wait_for_mysql
Fix Test and Lint
Docker compose command with dash is now deprecated. Fixing.
> Fix Test and Lint
